CREATE TABLE IF NOT EXISTS payments (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    client_id BIGINT NOT NULL ,
    client_account VARCHAR(20) NOT NULL ,
    receive_account VARCHAR(20) NOT NULL ,
    amount DOUBLE PRECISION NOT NULL ,
    okved_category VARCHAR(20),
    intra_bank_transfer BOOLEAN,
    receive_client_bank_bik VARCHAR(20) NOT NULL
);